package:
  name: q2_perc_norm
  version: 1.0

source:
  git_rev: v1.0
  git_url: https://github.com/cduvallet/q2-perc-norm.git

# Add bioconda channel for biom
extra:
  channels:
    - conda-forge
    - bioconda

requirements:
#  host:
#    - python
#    - setuptools

  build:
    - python
    - setuptools

  run:
    - python
    # QIIME 2 things for the setup
    - qiime2
    - q2-types
    # Other modules used in the actual code
    - biom-format
    - pandas
    - numpy
    - scipy

#test:
#  imports:
#    -


about:
  home: https://github.com/cduvallet/q2-perc-norm
  license: BSD-3-Clause
  license_family: BSD
